<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**John Benedict Aquino**

In [1]:
import numpy as np
A=np.array([[4,10,8],[10,26,26],[8,26,61]]) #matrix A
print(A)
A_inv=np.linalg.inv(A) #inverse of matrix A
print(A_inv)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]


In [2]:
B=np.array([[44],[128],[214]])#Constants
print(B)

[[ 44]
 [128]
 [214]]


In [3]:
X=np.dot(A_inv,B) #dot product of inversed matrix A and constants to get the missing variables x,y,z
print(X)

[[-8.]
 [ 6.]
 [ 2.]]


**Answer: x=-8, y=6, z=2**