<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**John Benedict Aquino** 201914430

In [ ]:
#Problem #1
#-x+z=6
#-y+3z=0
#x+y+z=89

import numpy as np
A=np.array([[-1,0,1],[0,-1,3],[1,1,1]]) #matrix A
print(A)
A_inv=np.linalg.inv(A) #inverse of matrix A
print(A_inv)

[[-1  0  1]
 [ 0 -1  3]
 [ 1  1  1]]
[[-0.8  0.2  0.2]
 [ 0.6 -0.4  0.6]
 [ 0.2  0.2  0.2]]


In [ ]:
B=np.array([[6],[0],[89]])#Constants
print(B)

[[ 6]
 [ 0]
 [89]]


In [ ]:
X=np.dot(A_inv,B) #dot product of inversed matrix A and constants to get the missing variables x,y,z
print(X)

[[13.]
 [57.]
 [19.]]


Final Answer: Student A has 13 cash, Student B has 57 cash, and Student C has 19 cash for a total of 89 cash.

In [ ]:
#Problem #2

import numpy as np
from scipy.linalg import solve
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
B = np.array([[5],[15],[-20]])
print(A)
print(B)
X=np.linalg.solve(A,B)
print(X)


[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


LinAlgError: ignored

Explanantion: The error occured because the determinant of the matrix A is equal to zero, which made the matrix A a singular matrix, meaning it has no inverse such that it has no multiplicative inverse.

In [ ]:
#Problem 3
A=np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)
s,t=np.linalg.eig(A)
print("Eigenvalues:",s.round())
print("Eigenvectors: ",t.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
Eigenvalues: [-1.  3.  2.]
Eigenvectors:  [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
