<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**John Benedict Aquino**

In [3]:
import numpy as np
A=np.array([[4,3,2],[-2,2,3],[3,-5,2]]) #matrix A
print(A)
A_inv=np.linalg.inv(A) #inverse of matrix A
print(A_inv)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]


In [6]:
B=np.array([[25],[-10],[-4]])#Constants
print(B)

[[ 25]
 [-10]
 [ -4]]


In [10]:
X=np.dot(A_inv,B) #dot product of inversed matrix A and constants to get the missing variables x,y,z
print(X)

[[ 5.]
 [ 3.]
 [-2.]]


**Answer: x=5, y=3, z=-2**