<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python Program to Inverse

###John Benedict Aquino

In [32]:
import numpy as np
A = np.array([[2,3,4],
              [8,4,5],
              [7,8,6]])
invA=np.linalg.inv(A)
print(invA)

[[-0.21917808  0.19178082 -0.01369863]
 [-0.17808219 -0.21917808  0.30136986]
 [ 0.49315068  0.06849315 -0.21917808]]


In [34]:
B = np.dot(A,invA)
print(B)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.11022302e-16  1.00000000e+00]]


In [14]:
##Python Program to Inverse a 3x3 Matrix A=([[6,1,1],[4,-2,5],[2,8,7]])
import numpy as np
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


In [13]:
B= np.linalg.inv(A)
print(B)

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [15]:
C=np.transpose(A)
print(C)

[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [17]:
D=np.dot(A,B)
print(D)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


In [19]:
productAB=A*B
print(productAB)

[[ 1.05882353 -0.00326797 -0.02287582]
 [ 0.23529412  0.26143791  0.4248366 ]
 [-0.23529412  1.20261438  0.36601307]]


##Coding Activity 3

In [43]:
##Create a Python Program to inverse and transpose a 4x4 matrix.
import numpy as np
A=np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
print(A)

[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]


In [44]:
#Inverse A
B=np.linalg.inv(A)
print(B)


[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


In [45]:
#Transpose A
C=np.transpose(A)
print(C)

[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
