<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Midterm Exam**

John Benedict Aquino Linear Algebra 58019

In [64]:
#Question 1. Create a Python code that displays a square matrix whose length is 5 
import numpy as np
A = np.array([[2,4,5,6,7],[6,7,3,5,8],[3,6,7,8,9],[1,4,5,7,8],[3,5,7,8,1]])
print(A)

[[2 4 5 6 7]
 [6 7 3 5 8]
 [3 6 7 8 9]
 [1 4 5 7 8]
 [3 5 7 8 1]]


In [65]:
#Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero
import numpy as np
A = np.array([[2,4,5,6,7],[0,7,3,5,8],[0,0,7,8,9],[0,0,0,7,8],[0,0,0,0,1]])
print(A)

[[2 4 5 6 7]
 [0 7 3 5 8]
 [0 0 7 8 9]
 [0 0 0 7 8]
 [0 0 0 0 1]]


In [66]:
#Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)
import numpy as np
A = np.array([[1,3,6],[3,7,5],[6,5,8]])
print(A)

[[1 3 6]
 [3 7 5]
 [6 5 8]]


In [67]:
#Question 4. What is the inverse of matrix C? Show your solution by python coding. 
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #Matrix C
print(C)


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]


In [68]:
C_inv=np.linalg.inv(C) #Inverse of Matrix C
print(C_inv)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [69]:
#Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding.
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #Matrix C
print('Determinant =',round(np.linalg.det(C))) #Determinant of Matrix C

Determinant = 5


In [70]:
#Question 6. Find the roots of the linear equations by showing its python codes
#5X1 + 4X2 + X3 = 3.4
#10X1 + 9X2 + 4X3 = 8.8
#10X1 + 13X2 + 15X3 = 19.2

import numpy as np
A=np.array([[5,4,1],[10,9,4],[10,13,15]]) #Matrix A of Linear Equations
print(A)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]


In [71]:
B = np.array([[3.4],[8.8],[19.2]]) #Constants
print(B)

[[ 3.4]
 [ 8.8]
 [19.2]]


In [72]:
A_inv=np.linalg.inv(A) #Inverse of matrix A 
print(A_inv)

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]


In [73]:
X=np.dot(A_inv,B) #Formula to get the missing variable X1, X2, AND X3
print(X)

[[0.2]
 [0.4]
 [0.8]]


X1=0.2, X2=0.4, X3=0.8