<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Practical Lab Exam 1**

**John Benedict Aquino**

In [67]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [11]:
B = np.array([[1,2,],[3,4],[5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(C)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
D = np.array([[1,2],[3,4]])
print(D)

[[1 2]
 [3 4]]


In [19]:
#Problem 1 A
print(A*B) #Matrices with different dimensions can't be multiplied

ValueError: ignored

In [20]:
#Problem 1 B
print(D+D)

[[2 4]
 [6 8]]


In [29]:
#Problem 1 C
print(2*C)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [32]:
#Problem 2
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [33]:
y = np.array([[3],[4],[5]])
print(y)

[[3]
 [4]
 [5]]


In [34]:
z = np.array([[7],[8],[9]])
print(z)

[[7]
 [8]
 [9]]


In [62]:
θ = 5*x+3*y-z
print(θ)

[[ 7]
 [14]
 [21]]


In [66]:
#Shape, Dimension, Type
print("shape = ",θ.shape)
print("dimensions = ",θ.ndim)
print("type = ",  type(θ))

shape =  (3, 1)
dimensions =  2
type =  <class 'numpy.ndarray'>
