<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Prelim Exam**

John Benedict Aquino 58019

Question 1

In [13]:

import numpy as np
C = np.eye(4,4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 2

In [6]:
import numpy as np
C = np.eye(4,4)
print(2*C)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question 3

In [10]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,6])
CP = np.cross(A,B)
print(CP)

[ 6  0 -3]
