<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Representing Vectors#

John Benedict Aquino

In [3]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


#Describing Vectors in Numpy

In [15]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
print(pool.shape)
print(pool.ndim)

(2, 3)
2


In [14]:
U = np.array([[1,2,3],[4,5,6]])
print(U.ndim)
print(U.size)

2
6


#Spaces

##Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations##

###Addition of Vectors###

In [16]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
print(sum)

[1 1 0]


In [18]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
Resultant = np.add(addend1,addend2)
print(Resultant)

[1 1 0]


##Subtraction of Vector

In [20]:
difference = addend1 - addend2
print(difference)

[-1 -1  0]


In [23]:
difference2 = np.subtract(addend1,addend2)
print(difference2)

[-1 -1  0]


##Scaling

In [ ]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

**Cross product**

In [26]:
import numpy as np
#initialize arrays
A = np.array([2,3,4])
B = np.array ([1,7,1])
#compute cross product
cross = np.cross(A,B)
print(cross)


11


In [27]:
A = np.array([2,3])
B = np.array ([1,7])
dot = np.dot(A,B)
print(dot)

23
