<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Matrix and Its Operations**


In [2]:
import numpy as np
A =np.array([[-5,0],[4,1]])
print(A)

[[-5  0]
 [ 4  1]]


In [3]:
B = np.array([[6,-3],[2,3]])
print(B)

[[ 6 -3]
 [ 2  3]]


In [6]:
sum = A+B #This is the operation for addition
print(sum)

[[ 1 -3]
 [ 6  4]]


In [7]:
difference1= B-A #This is an operation for subtraction
print(difference1)

[[11 -3]
 [-2  2]]


In [8]:
difference2 = A-B #This is also an operation for subtraction
print(difference2)

[[-11   3]
 [  2  -2]]
