<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-58019/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra

In [2]:
#numpy
import numpy as np
a = np.array([1,2,3]) #example of a 1x3 matrix
print(a)

[1 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [27]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c-c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
d = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
d1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d1)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [26]:
e = np.full( (3,3),7)
print(e)
print(e+e)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [20]:
f=np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
g = np.zeros((6,6))
print(g)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
h = np.empty((0,10))
print(h)

[]
